# -*- coding: utf-8 -*-
"""DLassignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tYZcYWtFhw-pkuoe9W2OjjHl_iBOg-Sf
"""

pip install scikeras tensorflow

"""# Imports

"""

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error

print("TensorFlow:", tf.__version__)

"""# Load Data and Split into X & y"""

data = pd.read_csv("housing.csv", sep="\s+", header=None)

X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

print("X shape:", X.shape)
print("y shape:", y.shape)

"""# Define Two Hidden Layer MLP"""

def build_model():
    model = keras.Sequential([
        keras.Input(shape=(13,)),
        layers.Dense(64, activation="relu"),
        layers.Dense(32, activation="relu"),
        layers.Dense(1)
    ])

    model.compile(
        optimizer="adam",
        loss="mse"
    )

    return model

"""# 10-Fold Cross Validation"""

kf = KFold(n_splits=10, shuffle=True, random_state=42)

mse_scores = []

for train_index, test_index in kf.split(X):

    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

    # Standardize inside each fold
    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)

    model = build_model()

    model.fit(
        X_train, y_train,
        epochs=100,
        batch_size=16,
        verbose=0
    )

    y_pred = model.predict(X_test, verbose=0)

    mse = mean_squared_error(y_test, y_pred)
    mse_scores.append(mse)

print("Two Hidden Layer MLP Results")
print("Mean MSE:", np.mean(mse_scores))
print("Std:", np.std(mse_scores))

"""# Single Hidden Layer"""

def build_single_hidden(units):
    model = keras.Sequential([
        keras.Input(shape=(13,)),
        layers.Dense(units, activation="relu"),
        layers.Dense(1)
    ])

    model.compile(optimizer="adam", loss="mse")
    return model

for units in [8, 16, 32, 64, 128]:

    kf = KFold(n_splits=10, shuffle=True, random_state=42)
    mse_scores = []

    for train_index, test_index in kf.split(X):

        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = y[train_index], y[test_index]

        scaler = StandardScaler()
        X_train = scaler.fit_transform(X_train)
        X_test = scaler.transform(X_test)

        model = build_single_hidden(units)
        model.fit(X_train, y_train, epochs=100, batch_size=16, verbose=0)

        y_pred = model.predict(X_test, verbose=0)
        mse_scores.append(mean_squared_error(y_test, y_pred))

    print(f"Units: {units}, Mean MSE: {np.mean(mse_scores):.2f}")

"""# Arbitrary Depth Network"""

def build_deep_model(hidden_layers):

    model = keras.Sequential()
    model.add(keras.Input(shape=(13,)))

    for units in hidden_layers:
        model.add(layers.Dense(units, activation="relu"))

    model.add(layers.Dense(1))

    model.compile(optimizer="adam", loss="mse")

    return model

"""# Test Different Depths"""

architectures = [
    [64],
    [64, 32],
    [64, 32, 16],
    [128, 64, 32, 16]
]

for arch in architectures:

    kf = KFold(n_splits=10, shuffle=True, random_state=42)
    mse_scores = []

    for train_index, test_index in kf.split(X):

        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = y[train_index], y[test_index]

        scaler = StandardScaler()
        X_train = scaler.fit_transform(X_train)
        X_test = scaler.transform(X_test)

        model = build_deep_model(arch)
        model.fit(X_train, y_train, epochs=100, batch_size=16, verbose=0)

        y_pred = model.predict(X_test, verbose=0)
        mse_scores.append(mean_squared_error(y_test, y_pred))

    print(f"Architecture {arch} → Mean MSE: {np.mean(mse_scores):.2f}")